import {StyleSheet} from 'react-native';
import {RFPercentage} from 'react-native-responsive-fontsize';

export default StyleSheet.create({
   
      searchBar: {
        flex: 1,
        flexDirection: 'row',
        color: 'white',
        width: '60%',
        height: '80%',
        fontSize: RFPercentage(1.5),
        marginTop: '5%',
        marginRight: '6%',
        marginLeft: '2%',
        borderRadius: 15,
        borderWidth: 3,
        borderColor: 'grey',
        paddingLeft: '6%',
        padding: '0.8%',
      },
      separator: {
        width: '90%',
        height: 3,
        backgroundColor: 'white',
        borderRadius: 30,
        alignSelf: 'center',
      },
      
      container2: {
        marginTop: '12%',
        margin: '5%',
        alignItems: 'center',
        flexDirection: 'column',
        width: '90%',
        backgroundColor: 'rgba(0, 0, 0, 0.93)',
        borderRadius: 15,
        height: '85%',
        borderWidth: 3,
        borderColor: 'white',
      },
      status: {
        justifyContent: 'flex-start',
        alignItems: 'center',
        flexDirection: 'row',
        width: '90%',
        marginTop: '3%',
      },
      gender: {
        justifyContent: 'space-between',
        alignItems: 'center',
        flexDirection: 'column',
        width: '90%',
        backgroundColor: '#d9dbda',
      },
      apply: {
        fontSize: RFPercentage(2),
        padding: 10,
        borderRadius: 15,
        marginTop: '8%',
        fontWeight: 'bold',
        borderColor: 'white',
        color: 'white',
        borderWidth: 2,
        alignSelf: 'center',
      },
      filter: {
        marginTop: '12%',
        borderColor: 'black',
        width: '10%',
        justifyContent: 'flex-end',
        marginRight: '10%',
        marginLeft: '10%',
      },
      filterText: {
        alignSelf: 'center',
        fontSize: RFPercentage(10),
      },
      inputContainer: {
        flexDirection: 'row',
        width: '100%',
      },
      text2: {
        padding: 5,
        marginTop: '5%',
        fontSize: RFPercentage(1.9),
        width: '20%',
        fontWeight: 'bold',
        color: 'white',
      },
      text3: {
        alignSelf: 'flex-start',
        padding: 2,
        marginLeft: '2%',
        fontSize: RFPercentage(1.9),
        marginTop: '5%',
        fontWeight: 'bold',
        color: 'white',
        width: '30%',
      },
      box: {
        borderColor: 'grey',
        borderWidth: 3,
        width: '26%',
        marginHorizontal: '1%',
        padding: 5,
        borderRadius: 15,
        alignItems: 'center',
      },
      boxSelected: {
        borderColor: 'grey',
        borderWidth: 3,
        width: '26%',
        marginHorizontal: '1%',
        padding: 5,
        borderRadius: 15,
        alignItems: 'center',
        backgroundColor: 'grey',
      },
      status2: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: '3%',
      },
      box2: {
        borderColor: 'grey',
        borderWidth: 3,
        width: '31%',
        marginHorizontal: '1%',
        padding: 5,
        borderRadius: 15,
        alignItems: 'center',
      },
      box2Selected: {
        borderColor: 'grey',
        borderWidth: 3,
        width: '31%',
        marginHorizontal: '1%',
        padding: 5,
        borderRadius: 15,
        alignItems: 'center',
        backgroundColor: 'grey',
      },
      options: {
        marginVertical: '5%',
        marginTop: '5%',
        marginBottom: '10%',
      },
      separator2: {
        width: '75%',
        height: '1%',
        backgroundColor: 'white',
        borderRadius: 30,
        alignSelf: 'center',
        marginTop: '14%',
      },
      buttons: {
        color: 'white',
        fontSize: RFPercentage(1.6),
      },
});