import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  search: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: '5%',
    marginBottom: '3%',
    width: '80%',
    height: '5%',
  },
  searchbar: {
    backgroundColor: 'white',
    flex: 1,
    flexDirection: 'row',
    width: '70%',
    fontSize: 18,
    fontWeight: 'bold',
    borderRadius: 20,
    paddingLeft: '6%',
  },
  separator: {
    width: '90%',
    height: 3,
    backgroundColor: 'white',
    borderRadius: 30,
    alignSelf: 'center',
  },
  filter_icon: {
    width: '10%',
    marginLeft: '5%',
    height: '100%',
    borderRadius: 30,
    color: 'white',
    justifyContent: 'space-evenly',
    fontSize: 30,
    textAlign: 'center',
    textAlignVertical: 'center',
    backgroundColor: 'black',
  },
  loader: {
    width: '100%',
    backgroundColor: 'rgba(255,255,255,1)',
    height: '25%',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loaderactivity: {
    flex: 1,
  },
  container2: {
    marginTop: 70,
    margin: 15,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'column',
    width: '90%',
    backgroundColor: '#d9dbda',
    borderRadius: 15,
    height: 600,
  },
  status: {
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
    width: '90%',
    backgroundColor: '#d9dbda',
  },
  gender: {
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'column',
    width: '90%',
    backgroundColor: '#d9dbda',
  },
  searchBar__clicked: {
    padding: 10,
    width: '95%',
    height: 40,
    flexDirection: 'row',
    backgroundColor: '#d9dbda',
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'space-evenly',
  } /*
  input: {
    fontSize: 30,
    marginLeft: 10,
    width: '90%',
  },
 */,
  x: {
    fontSize: 30,
    padding: 10,
    fontWeight: 'bold',
    borderColor: 'black',
    borderWidth: 3,
    alignSelf: 'center',
    backgroundColor: 'grey',
  } /*,
   ,
  info: {
    fontSize: 20,
    padding: 10,
    marginLeft: 30,
  },
  button: {
    marginBottom: 10,
    marginRight: 5,
    width: 50,
    height: 60,
    backgroundColor: 'grey',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: 'black',
    borderWidth: 2,
    alignSelf: 'flex-end',
    borderRadius: 20,
  },,
  buttonText: {
    padding: 10,
    alignSelf: 'center',
    color: 'white',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    fontWeight: 'bold',
    fontSize: 20,
    textAlignVertical: 'center',
  },
*/,
  filter: {
    marginTop: '15%',
    borderColor: 'black',
    alignSelf: 'flex-end',
    borderWidth: 3,
    width: '10%',
    justifyContent: 'flex-end',
    borderRadius: 15,
    backgroundColor: 'grey',
    marginHorizontal: '12%',
  },
  filterText: {
    alignSelf: 'center',
    fontSize: 20,
  },
  inputContainer: {
    flexDirection: 'row',
    borderColor: 'grey',
    borderWidth: 3,
    width: '100%',
  },
  text2: {
    padding: 5,
    marginLeft: 0,
    fontSize: 17,
    fontWeight: 'bold',
  },

  text3: {
    alignSelf: 'flex-start',
    padding: 5,
    fontSize: 17,
    fontWeight: 'bold',
    width: '30%',
  },
  box: {
    borderColor: 'black',
    borderWidth: 3,
    width: '24%',
    marginHorizontal: 2,
    padding: 10,
  },
  status2: {
    flexDirection: 'row',
    //justifyContent: 'space-between',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  box2: {
    borderColor: 'black',
    borderWidth: 3,
    width: '32%',
    marginHorizontal: 2,
    padding: 10,
  },
  searchName: {
    //backgroundColor: 'grey',
    width: '70%',
    height: 40,
    marginTop: 50,
    flexDirection: 'row',
    backgroundColor: '#d9dbda',
    borderRadius: 15,
  },
  filtersContainer: {
    flexDirection: 'row',
    color: 'grey',
    marginHorizontal: '4%',
  },
});
